### ISSUE TITLE
Thay đổi phím tắt F2

### ISSUE THREAD

**Issue by quydo** [glmanhtu/VN_IME#12]
Admin cho mình hỏi muốn thay đổi phím tắt F2 thì làm như nào nhỉ :D

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Bạn chỉnh hotkey trong file Default.sublime-keymap nhé

Ref: https://github.com/yehnkay/VN_IME/blob/master/Default.sublime-keymap#L2

**Comment by quydo** [comment]
Thanks bác, em mò đc rồi :D 

Đang có lỗi là, em dùng vim extension, gán phím u là undo

Khi bật VN_IME, nếu undo bằng u thì các kí tự kiểu { cạnh con trỏ nó sẽ bị thành Ư, kiểu thế

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Bạn nên kiểm tra lại hotkey, đừng để hotkey nào bị trùng nhau.

Về lỗi, bạn có thể mô tả rõ hơn như demo 1 (vài) trường hợp lỗi. Mình 
set undo là ctrl+z và không thấy lỗi nào cả, trường hợp của bạn mình 
nghĩ nếu bạn chỉ set undo là duy nhất phím u thì sublime không nghĩ đó 
là function undo đâu, bạn có thể thử set ctrl+u

**Comment by quydo** [comment]
Default Ctrl+z ko sao, chắc do cái extension vim kia rồi

**Comment by chiendo1010** [comment]
Nghĩa là thêm dòng 
{ "keys": ["f2"], "command": "controlime" },
vào Preference / Key Bingling hả bạn?

Do tôi mới xài Ubuntu nên không rõ chỉ phím tắt/mở VN IME lại như thế nào. Do hiện tại nó bị trùng với Phím đi tới bookmark mặc định cua Sublime Text.

**Comment by zolaahihi** [comment]
Em qua dùng Windows và fix đc rồi. haha :D

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
@chiendo1010 bạn có thể thay thế hotkey bằng cách edit file `Default.sublime-keymap` trong thư mục plugin VN_IME (không phải trong Preference), ví dụ như của mình file này nằm ở `~/.config/sublime-text-3/Packages/VN_IME`

**Comment by chiendo1010** [comment]
@88d52bdba0366127fffca9dfa93895 : Cám ơn bạn, mình đã chỉnh được. của mình nó nằm trong 
/home/home/.config/sublime-text-3/Installed Packages.
